name: account-check
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "( contains(github.event.head_commit.message, 'run') || github.event_name == 'workflow_dispatch')"
    env: 
      nganu: ${{toJSON(github.event)}}
      ev_name: ${{github.event_name}}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_PAT}}

      - name: setup
        run: |
          sudo apt update > /dev/null; sudo apt -y install python3 python3-pip > /dev/null;
          sudo pip install -r requirements.txt
      - run: python3 check.py
      - name: push
        run: |
          git config --global user.email "git@github.com"; git config --global user.name "github-runner"
          git add .; git commit -m runner-update --allow-empty; git push -f
